server:
  port: 7777
  
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
     routes:
      - id: inventory-service-route
        uri: http://localhost:8081
        predicates:
        - Path=/products/**
      - id: order-service-route
        uri: http://localhost:8082
        predicates:
        - Path=/orders/**